# Generated by Django 5.0.6 on 2024-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.FileField(default='/Users/maria/Desktop/BetterReads/store/defaultFile.pdf', upload_to='products/'),
        ),
    ]
