# Generated by Django 5.0.6 on 2024-05-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_purchase_product_alter_purchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_illustrated',
            field=models.BooleanField(default=False),
        ),
    ]
