# Generated by Django 5.0.6 on 2024-06-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant_id',
            new_name='payment_intent',
        ),
    ]
